/**
 * Theme Configuration
 * Auto-generated by AppForge AI
 */

export const colors = {
  primary: {
  "50": "#F0FDFA",
  "100": "#CCFBF1",
  "200": "#99F6E4",
  "300": "#5EEAD4",
  "400": "#2DD4BF",
  "500": "#14B8A6",
  "600": "#0D9488",
  "700": "#0F766E",
  "800": "#115E59",
  "900": "#134E4A"
},
  secondary: {
  "50": "#F7F7F8",
  "100": "#F0F0F2",
  "200": "#DADBDF",
  "300": "#C3C6CC",
  "400": "#979CA6",
  "500": "#6B7280",
  "600": "#606673",
  "700": "#555B66",
  "800": "#4A4F59",
  "900": "#40444C"
},
  accent: {
  "50": "#ECFEFF",
  "100": "#CFFAFE",
  "200": "#A5F3FC",
  "300": "#67E8F9",
  "400": "#22D3EE",
  "500": "#06B6D4",
  "600": "#0891B2",
  "700": "#0E7490",
  "800": "#155E75",
  "900": "#164E63"
},
  neutral: {
  "50": "#FAFAFA",
  "100": "#F5F5F5",
  "200": "#E5E5E5",
  "300": "#D4D4D4",
  "400": "#A3A3A3",
  "500": "#737373",
  "600": "#525252",
  "700": "#404040",
  "800": "#262626",
  "900": "#171717"
},
  semantic: {
  "success": "#10B981",
  "warning": "#F59E0B",
  "error": "#EF4444",
  "info": "#3B82F6"
},
};

export const typography = {
  fontFamily: {
  "heading": "System",
  "body": "System",
  "mono": "Courier"
},
  scale: {
  "h1": {
    "fontSize": 32,
    "lineHeight": 40,
    "fontWeight": "700"
  },
  "h2": {
    "fontSize": 24,
    "lineHeight": 32,
    "fontWeight": "600"
  },
  "h3": {
    "fontSize": 20,
    "lineHeight": 28,
    "fontWeight": "600"
  },
  "h4": {
    "fontSize": 18,
    "lineHeight": 24,
    "fontWeight": "500"
  },
  "body": {
    "fontSize": 16,
    "lineHeight": 24,
    "fontWeight": "400"
  },
  "bodySmall": {
    "fontSize": 14,
    "lineHeight": 20,
    "fontWeight": "400"
  },
  "caption": {
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": "400"
  },
  "button": {
    "fontSize": 16,
    "lineHeight": 24,
    "fontWeight": "600"
  }
},
};

export const spacing = {
  base: 4,
  scale: [0,4,8,12,16,20,24,32,40,48,64],
};

export const animations = {
  duration: {
  "fast": 150,
  "normal": 300,
  "slow": 500
},
  easing: {
  "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "accelerate": "cubic-bezier(0.4, 0, 1, 1)",
  "decelerate": "cubic-bezier(0, 0, 0.2, 1)"
},
};

export default {
  colors,
  typography,
  spacing,
  animations,
};
